namespace CustomUnit.Additions;

public enum SpawnLocation
{
    Inside330,
    Inside330Chamber,
    Inside049Armory,
    Inside079Secondary,
    Inside096,
    Inside173Armory,
    Inside173Bottom,
    Inside173Connector,
    InsideEscapePrimary,
    InsideEscapeSecondary,
    InsideIntercom,
    InsideLczArmory,
    InsideLczCafe,
    InsideNukeArmory,
    InsideSurfaceNuke,
    Inside079First,
    Inside173Gate,
    Inside914,
    InsideGateA,
    InsideGateB,
    InsideGr18,
    InsideHczArmory,
    InsideHid,
    InsideHidLeft,
    InsideHidRight,
    InsideLczWc,
    InsideServersBottom,
    InsideClassDCell,
}